### ISSUE TITLE
[MIGLIORIA] Aggiunta analisi per utente

### ISSUE THREAD

**Issue by diegocampanella** [lapalice88/SBMM-Analysis#1]
Sarebbe possibile aggiungere la possibilità di analizzare le lobby per singolo utente?

Dando in input un ID Activision e un numero x di ultime partite giocate avere in output una singola analisi con i vari valori di K/D medio, minimo, max etc...

Ci sono le API di CoD che permetterebbero di fare lo scraping di tutti i player incontrati.

Diego

**Comment by lapalice88** [comment]
Caro Diego, grazie per l'interesse. Effettivamente stiamo lavorando in quella direzione con altre funzioni interessanti.

Abbiamo usato proprio quelle API per scaricare i dati e cercheremo di farlo anche per le migliorie.

A

**Comment by diegocampanella** [comment]
Grazie mille! Ne può uscire qualcosa di veramente interessante e utile ;)
